ROADS:
  - 1.2
  - 1.3
  - 2.1
  - 3.1
  - 3.2
COMBINATIONS:
  -
    - 1.2
    - 2.1
  -
    - 3.1
    - 3.2
  -
    - 1.3
    - 1.2
SWITCH_PENALTY: 1  # [s] unrealistic
CAMERA_DISTANCE: 50  # [m]
NUM_CARS: 5  # format should be changed to allow different number of cars between roads